version: '3.7'

services:
  default:
    build:
      context: ./python
    tty: true
    stdin_open: true
    ports:
      - 3000:8000
    volumes:
      - /etc/localtime:/etc/localtime
      - ~/.bashrc:/home/ubuntu/.bashrc
      - ~/.dotconfig:/home/ubuntu/.dotconfig
      - ~/wks/src:/home/ubuntu/wks/src

  postgres:
    build:
      context: ./postgres
      args:
        - POSTGRES_PASSWORD
    volumes:
      - db:/var/lib/postgresql/data

  phppgadmin:
    build:
      context: ./phppgadmin
    environment:
      - PHP_PG_ADMIN_SERVER_HOST=postgres
    ports:
      - 3001:80

  adminer:
    build:
      context: ./adminer
    environment:
      ADMINER_DEFAULT_SERVER: postgres
    ports:
      - 3002:8080

volumes:
  db:
